name: Publish and Release

on:
  push:
    branches:
     - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: mikeal/merge-release@master
